### ISSUE TITLE
Error in periodicity(x) : can not calculate periodicity of 1 observation

### ISSUE THREAD

**Issue by baditaflorin** [joshuaulrich/xts#155] opened 2016-10-10 20:26 UTC
`last` and `first` are not working as expected, showing only one value and not allowing me to show more than one value.

```r
> library(xts)
> tail(x)
[1] "2011-10-31 22:00:00 PDT" "2011-10-21 22:00:00 PDT"
[3] "2011-10-21 22:00:00 PDT" "2011-10-21 22:00:00 PDT"
[5] "2011-08-31 22:00:00 PDT" "1950-06-22 10:00:00 PDT"
> last(x)
[1] "1950-06-22 10:00:00 PDT"
> first(x)
[1] "2016-10-08 10:10:58 PDT"
> lastyears <- last(x, "1000 years")
Error in periodicity(x) : can not calculate periodicity of 1 observation
> firstyears <- first(x,"1000 years")
Error in periodicity(x) : can not calculate periodicity of 1 observation
```

**Comment by joshuaulrich** [comment] 2016-10-10 22:04
Please provide a [reproducible example](http://stackoverflow.com/q/5963269/271616). I cannot replicate this error with the code below using xts-0.9-7 from CRAN or xts-0.10-0 from GitHub.

```r
library(xts)
set.seed(21)
dt <- seq(as.POSIXct("1950-06-22 10:00:00", tz="America/Los_Angeles"),
          as.POSIXct("2016-10-08 10:10:58", tz="America/Los_Angeles"), "days")
dt <- dt[sample(length(dt))]
str(l <- last(dt, "1000 years"))
str(f <- first(dt, "1000 years"))
```

**Comment by joshuaulrich** [comment] 2016-10-29 22:05
Closing as invalid since I cannot replicate and the reporter is unresponsive.

**Closed by joshuaulrich** 2016-10-29 22:05 UTC
Labels: invalid
