### ISSUE TITLE
Licensing confusion

### ISSUE THREAD

**Issue by hyandell** [joshuaulrich/xts#195] opened 2017-06-26 20:41 UTC
### Description

The description file, xts.h/xtsAPI.h/xts-package.Rd say that the license is GPL 2+ (GPL >= 2).

Many of the source files though say the license is GPL 3+ (either version 3 of the License, or (at your option) any later version).

(Hopefully understandably) I'm a bit confused :)

Is the project useable under GPL 2.0, or only 3.0+?

**Comment by joshuaulrich** [comment] 2017-06-26 20:46
Closing as duplicate of #127.  As I said in my email (years ago), the license should be GPLv2+.

**Closed by joshuaulrich** 2017-06-26 20:46 UTC
Labels: duplicate

**Comment by hyandell** [comment] 2017-06-26 23:59
Sorry - I search issues for 'license' but not pull requests. Embarrassing that the previous one was from me :)

**Comment by joshuaulrich** [comment] 2017-06-27 00:01
No worries. This *did* prompt me to action!
