### ISSUE TITLE
Error in lag.xts

### ISSUE THREAD

**Issue by tchevri** [joshuaulrich/xts#180] opened 2017-04-18 06:42 UTC
Dear Josh,

I have been using your library and I thank you very much for that.
This xts is absolutely terrific.  I love it.
This said, I am hesitant / reluctant to write here (the issue is most likely that i don't really what i am doing), but i will give it a shot anyway - hopefully you will forgive me if i write any nonsense that aggravates you!

Couple of tentative comments for your kind perusal therefore.

1. I have been using

```r
> Return.calculate  function (prices, method = c("discrete", "log")) 
{
    method = method[1]
    pr = checkData(prices, method = "xts")
    if (method == "simple" || method == "discrete") {
        Returns = pr/lag.xts(pr) - 1
        xtsAttributes(Returns) <- list(ret_type = "discrete")
    }
    if (method == "compound" || method == "log") {
        Returns = diff(log(pr))
        xtsAttributes(Returns) <- list(ret_type = "log")
    }
    reclass(Returns, match.to = pr)
}
<environment: namespace:PerformanceAnalytics>
```
without any issues for the longest time - as far as your 0.9.874 xts package as a matter of fact.
Because I have had so many issues with `plot.xts` (see point 2 below), i thought i'd try living on the egde and rather than using the cran package, I went for 

```r
devtools::install_github("joshuaulrich/xts")
```

and so i had 0.10 installed...  the above function stopped working when used in the following line:

```r
TR.Data <- Return.calculate(TRI.Data)
Error in lag.xts(pr) : 
  INTEGER() can only be applied to a 'integer', not a 'double'
```

(TRI.Data is simply index return data from Bloomberg, and obviously, I am calculating the total return here from the index data:  TRI = total return index.  TR = Total return)
To be clear, this line, using Return.calculate works perfectly fine with 0.9.874, not with 0.10.0
The offense is clearly:

```r
xts:::lagts.xts(pr)
Error in xts:::lagts.xts(pr) : 
  INTEGER() can only be applied to a 'integer', not a 'double'
```

I am not sure how to fix this one - apologies.  Since it was fine in 0.9.874, I did not even know i was probably doing something wrong (this said, i checked - and the calculation was absolutely correct)

2. What really attracted me to xts in the very first place was this article:
https://www.r-bloggers.com/plot-xts-is-wonderful/

I find it very regrettable that it seems that there was a how to call it?  regression? and that none of the features advertised in this article seem to be available or am I just too blur to figure out the appropriate plot.xts that would allow me to access these plotting features?
in my code - i have two returns - an asset and its benchmark - i cbind them in a single xts object (so 2 columns + dates).  and i can't even seem to be able to plot...  In an earlier version, xts::plot.xts seemed to work - as a matter of fact i was using it!- , but now all of a sudden, i don't even know what i changed, i can't plot at all with xts::plot.xts.  and indeed, i checked the source code and there is a line that will throw an error when NCOL > 1...  So i had to remove all my xts::plot.xts references and replace with chart.TimeSeries instead, which works just fine (but i worry i am using another library for no reason - and maybe i should be using xts instead!?)

Sorry for being verbious - but given that i am not well versed in R - i figured i'd try to be as explicit as possible.

thanks for any help or insights you may provide.
thomas

fyi - i am not providing system references since it's not very relevant - i use the code on various platforms.. but fyi, i am on the latest R, 3.3.3, all up to date.  64 bits, etc.. happy to share any desired info on that front.

**Comment by joshuaulrich** [comment] 2017-04-21 19:15
You may not think system references are relevant, but I need them in order to help you.  All the things that aren't working for you, work just fine for me.

You don't provide a sample of `TRI.Data`, so I have to create some example date to try and replicate your reported issue.  And when I do that, I cannot replicate the issue.  So it could be with the data, or your system configuration, or something else...

```r
library(PerformanceAnalytics)
data(sample_matrix)
TRI.Data <- as.xts(sample_matrix, dateFormat="Date")
TR.Data <- Return.calculate(TRI.Data)
#                     Open          High           Low         Close
# 2007-01-02            NA            NA            NA            NA
# 2007-01-03  0.0038112533  6.067683e-03  0.0056071918  5.584627e-03
# 2007-01-04  0.0037917008 -1.826178e-05  0.0006697200 -1.295878e-03
# 2007-01-05 -0.0009418139 -9.418139e-04 -0.0008575248  4.446036e-05
# 2007-01-06 -0.0025637015 -2.563701e-03 -0.0021868581 -3.049073e-03
# 2007-01-07 -0.0022333512 -5.714886e-04 -0.0023817636 -3.771668e-03
```

**Comment by long-jian** [comment] 2017-05-15 06:57
Hi, Josh

I am facing the same problem when I was trying to run the Turtle demo of blotter.

```
  Error in lag.xts(HLC[, 3]) : 
  INTEGER() can only be applied to a 'integer', not a 'double'
```
And this error is also reproducible of the sample_matrix. The error like of my computer like below. 

```
>library(PerformanceAnalytics)
>data(sample_matrix)
>TRI.Data <- as.xts(sample_matrix, dateFormat="Date")
>TR.Data <- Return.calculate(TRI.Data)
Error in lag.xts(pr) : 
  INTEGER() can only be applied to a 'integer', not a 'double'
```

My `sessionInfo()` output is:

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950  LC_CTYPE=Chinese (Traditional)_Taiwan.950   
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950 LC_NUMERIC=C                                
[5] LC_TIME=Chinese (Traditional)_Taiwan.950    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] blotter_0.9.1644           FinancialInstrument_1.2.0  quantmod_0.4-8             TTR_0.23-1                
[5] PerformanceAnalytics_1.5.1 devtools_1.12.0            xts_0.10-0                 zoo_1.8-1                 

loaded via a namespace (and not attached):
 [1] lattice_0.20-33 digest_0.6.9    withr_1.0.2     grid_3.3.1      R6_2.1.2        git2r_0.15.0    httr_1.2.1      curl_1.0       
 [9] tools_3.3.1     memoise_1.0.0 
```

**Comment by joshuaulrich** [comment] 2017-05-15 16:56
Hi @long-jian, thanks for the comment!  I'm still not able to reproduce this using the latest development version of xts on GitHub.  I've tried on 64-bit Ubuntu using R-3.4.0 and 64-bit Windows 7 using R-3.3.2 (in both 64- and 32-bit versions of R).

Can you please try re-installing xts from GitHub to ensure you're using the latest development version of xts?

**Comment by long-jian** [comment] 2017-05-16 09:08
@joshuaulrich That works! After re-installed xts from GitHub, I can run the example without error message. Thanks for your helping. 

May I translate "turtles.R", blotter demo, to Chinese?  Just for education and introducing for blotter.

**Comment by joshuaulrich** [comment] 2017-05-16 11:25
@long-jian Thank you for verifying that it works with the current development version! I'm closing this issue as invalid, since it's not an issue with the most current code.

The xts issue tracker isn't the place to discuss translating the blotter demo.  Please email me and @braverock directly.

**Closed by joshuaulrich** 2017-05-16 11:25 UTC

**Comment by nathalok** [comment] 2017-05-18 03:56
Hi Josh, I was able to reproduce the issue. The steps along with the output of sessionInfo command is provided below. 

 > >data(sample_matrix)
 > > TRI.Data <- as.xts(sample_matrix, dateFormat="Date")
 > > TR.Data <- Return.calculate(TRI.Data)
 > Error in lag.xts(pr) : 
 >   INTEGER() can only be applied to a 'integer', not a 'double'
> 
> 
> sessionInfo()
> R version 3.4.0 (2017-04-21)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 8.1 x64 (build 9600)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
> [5] LC_TIME=English_Australia.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] quantstrat_0.10.0          foreach_1.4.4              blotter_0.11.3             PerformanceAnalytics_1.5.1 FinancialInstrument_1.2.0  quantmod_0.4-8            
> [7] TTR_0.23-1                 xts_0.10-0                 zoo_1.8-0                 
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.4.0   tools_3.4.0      codetools_0.2-15 grid_3.4.0       iterators_1.0.8  boot_1.3-19      lattice_0.20-35

**Comment by nathalok** [comment] 2017-05-18 03:59
Not sure how to open this issue!

**Comment by joshuaulrich** [comment] 2017-05-18 14:02
Hi @nathalok, you cannot re-open an issue. Only me or the original author can re-open the issue.

Did you re-install xts fom the most current commit from this repository using either:

```r
remotes::install_github("joshuaulrich/xts")
# or
devtools::install_github("joshuaulrich/xts")
```

**Comment by tchevri** [comment] 2017-05-18 16:32
So sorry guys. See your emails and dying to chime in. I could reproduce the issue too. Works with  <10.0. Fails with 10.0Clearly a 10.0 issue.Because of your President Trump sending the markets havoc had to work 20h a day.... so will try to get back to you asp. Apologies.Thomas





-------- Original message --------From: nathalok <notifications@github.com> Date: 5/18/17  12:56  (GMT+09:00) To: joshuaulrich/xts <xts@noreply.github.com> Cc: tchevri <tchevri@gmail.com>, Author <author@noreply.github.com> Subject: Re: [joshuaulrich/xts] Error in lag.xts (#180) 
Hi Josh, I was able to reproduce the issue. The steps along with the output of sessionInfo command is provided below.


data(sample_matrix)

TRI.Data <- as.xts(sample_matrix, dateFormat="Date")

TR.Data <- Return.calculate(TRI.Data)

Error in lag.xts(pr) :

INTEGER() can only be applied to a 'integer', not a 'double'

sessionInfo()

R version 3.4.0 (2017-04-21)

Platform: x86_64-w64-mingw32/x64 (64-bit)

Running under: Windows 8.1 x64 (build 9600)
Matrix products: default
locale:

[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C

[5] LC_TIME=English_Australia.1252
attached base packages:

[1] stats     graphics  grDevices utils     datasets  methods   base
other attached packages:

[1] quantstrat_0.10.0          foreach_1.4.4              blotter_0.11.3             PerformanceAnalytics_1.5.1 FinancialInstrument_1.2.0  quantmod_0.4-8

[7] TTR_0.23-1                 xts_0.10-0                 zoo_1.8-0
loaded via a namespace (and not attached):

[1] compiler_3.4.0   tools_3.4.0      codetools_0.2-15 grid_3.4.0       iterators_1.0.8  boot_1.3-19      lattice_0.20-35


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/joshuaulrich/xts","title":"joshuaulrich/xts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/joshuaulrich/xts"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nathalok in #180: Hi Josh, I was able to reproduce the issue. The steps along with the output of sessionInfo command is provided below. \r\n\r\n \u003e \u003edata(sample_matrix)\r\n \u003e \u003e TRI.Data \u003c- as.xts(sample_matrix, dateFormat=\"Date\")\r\n \u003e \u003e TR.Data \u003c- Return.calculate(TRI.Data)\r\n \u003e Error in lag.xts(pr) : \r\n \u003e   INTEGER() can only be applied to a 'integer', not a 'double'\r\n\u003e \r\n\u003e \r\n\u003e sessionInfo()\r\n\u003e R version 3.4.0 (2017-04-21)\r\n\u003e Platform: x86_64-w64-mingw32/x64 (64-bit)\r\n\u003e Running under: Windows 8.1 x64 (build 9600)\r\n\u003e \r\n\u003e Matrix products: default\r\n\u003e \r\n\u003e locale:\r\n\u003e [1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      \r\n\u003e [5] LC_TIME=English_Australia.1252    \r\n\u003e \r\n\u003e attached base packages:\r\n\u003e [1] stats     graphics  grDevices utils     datasets  methods   base     \r\n\u003e \r\n\u003e other attached packages:\r\n\u003e [1] quantstrat_0.10.0          foreach_1.4.4              blotter_0.11.3             PerformanceAnalytics_1.5.1 FinancialInstrument_1.2.0  quantmod_0.4-8            \r\n\u003e [7] TTR_0.23-1                 xts_0.10-0                 zoo_1.8-0                 \r\n\u003e \r\n\u003e loaded via a namespace (and not attached):\r\n\u003e [1] compiler_3.4.0   tools_3.4.0      codetools_0.2-15 grid_3.4.0       iterators_1.0.8  boot_1.3-19      lattice_0.20-35 \r\n"}],"action":{"name":"View Issue","url":"https://github.com/joshuaulrich/xts/issues/180#issuecomment-302293869"}}}

**Comment by tchevri** [comment] 2017-05-19 14:38
i have a bit more time now.
I will try to send the code.
it works perfectly fine with 0.9.874.
Upgrading to 0.10.0 breaks the code.
fyi, i upgrade via devtools, as indicated on github

**Comment by joshuaulrich** [comment] 2017-05-19 19:27
@tchevri Can you please provide the output from `sessionInfo()`?  If you're running R through RStudio, can you try running R from the GUI it comes with, or from the terminal?  And if you're on Windows, make sure there are no other R processes running on the computer when you upgrade xts.

**Comment by tchevri** [comment] 2017-05-21 16:41
I am no longer able to reproduce the error - thanks a lot for resolving this - whatever you did (and if you did not do anything over the last week, then a clean install seems to be the solution).  Here's the code for your kind perusal, which i wrote to hope reproducing the issue....

`install.packages('xts', repos="http://download.r-forge.r-project.org", type="source", dependencies=TRUE)
##  So this installs xts_0.9.874
# ** testing if installed package can be loaded
# *** arch - i386
# *** arch - x64
# * DONE (xts)
library('xts', character.only=T)
##  So this installs xts_0.9.874
get(".__S3MethodsTable__.", envir = baseenv())$print.object
##  Following https://stat.ethz.ch/pipermail/r-devel/2015-December/072150.html
for (package in c('PerformanceAnalytics', 'quantmod')) {
  if (!require(package, character.only=T, quietly=T)) {
    cat("\n\n", package, "Package missing \nPlease download package from Server \nInstalling from R-forge:")
    install.packages(package, repos="http://R-Forge.R-project.org")
    library(package, character.only=T)
  }
}
## Get a sample FX series, how about USDJPY?
getFX("USD/JPY",from="2005-01-01", to = "2017-05-18")
tail(USDJPY)  ## let's take a look at the series that was created: bit odd... this is cleary JPY/USD, but ok...
# USD.JPY
# 2017-05-13 113.3375
# 2017-05-14 113.3375
# 2017-05-15 113.4905
# 2017-05-16 113.4336
# 2017-05-17 112.1126
# 2017-05-18 111.0077
eUSDJPY <- Return.calculate(USDJPY)  ## PerformanceAnalytics package - great complement to xts
tail(eUSDJPY)  ## works perfectly
# USD.JPY
# 2017-05-13 -0.0024408788
# 2017-05-14  0.0000000000
# 2017-05-15  0.0013499063
# 2017-05-16 -0.0005012755
# 2017-05-17 -0.0116454026
# 2017-05-18 -0.0098551345

## OK - so let's upgrade xts
detach("package:quantmod", unload=TRUE)
detach("package:PerformanceAnalytics", unload=TRUE)
detach("package:TTR", unload=TRUE)
detach("package:xts", unload=TRUE)
rm(list="print.xts", envir = get(".__S3MethodsTable__.", envir =
                                      baseenv()))
devtools::install_github("joshuaulrich/xts")
##  So this installs xts_0.10.0
# ** testing if installed package can be loaded
# *** arch - i386
# *** arch - x64
# * DONE (xts)
for (package in c('PerformanceAnalytics', 'quantmod')) {
  if (!require(package, character.only=T, quietly=T)) {
    cat("\n\n", package, "Package missing \nPlease download package from Server \nInstalling from R-forge:")
    install.packages(package, repos="http://R-Forge.R-project.org")
    library(package, character.only=T)
  }
}
# Loading required package: xts
# Error: package or namespace load failed for ‘xts’ in get(method, envir = home):
#   lazy-load database 'D:/Thomas/Documents/TEACHING/ESSEC/Econometrics/HWK/TC/Windows/packrat/lib/x86_64-w64-mingw32/3.4.0/xts/R/xts.rdb' is corrupt
# Error: package ‘xts’ could not be loaded

#######################
## So what i did was to close Rstudio
## I deleted the folder xts!!!!
## I restart Rstudio
## and I just keep running the code below....
#######################

devtools::install_github("joshuaulrich/xts")
for (package in c('PerformanceAnalytics', 'quantmod')) {
  if (!require(package, character.only=T, quietly=T)) {
    cat("\n\n", package, "Package missing \nPlease download package from Server \nInstalling from R-forge:")
    install.packages(package, repos="http://R-Forge.R-project.org")
    library(package, character.only=T)
  }
}
## Get a sample FX series, how about USDJPY?
getFX("USD/JPY",from="2005-01-01", to = "2017-05-18")
tail(USDJPY)  ## let's take a look at the series that was created: bit odd... this is cleary JPY/USD, but ok...
# USD.JPY
# 2017-05-13 113.3375
# 2017-05-14 113.3375
# 2017-05-15 113.4905
# 2017-05-16 113.4336
# 2017-05-17 112.1126
# 2017-05-18 111.0077
eUSDJPY <- Return.calculate(USDJPY)  ## PerformanceAnalytics package - great complement to xts
tail(eUSDJPY)  ## works perfectly

## And NO FAILURE...
## Hmmmmmmmm....

## So I go back to my original code, because this example SHOULD HAVE failed too!!!
## Note that clearly, I have xts10.0 installed now...
## And my code no longer fails....
## SO as far as I am concerned, the error was fixed.
## Not sure if on your end or if just reinstalling from scratch did it.
## Many thanks

Note, because of annoying Bloomberg, I am constrained to use WINDOWS.... instead of my preferred ubuntu partition....  not sure how to get blpapi working under linux as it requires running the bbcomm.exe app in the background, very frustrating and shared my frustration with bloomberg, but they did not buldge :-((

`
> sessionInfo()
R version 3.4.0 Patched (2017-05-10 r72670)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats4    grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Rblpapi_0.3.6                 fCopulae_3011.81              fMultivar_3022.79            
 [4] Rnlminb2_3002.10              PerformanceAnalytics_1.4.4000 Rsocp_271.1                  
 [7] dplR_1.6.5                    R.utils_2.5.0                 R.oo_1.21.0                  
[10] R.methodsS3_1.7.1             quantmod_0.4-8                energy_1.7-0                 
[13] ecodist_1.2.9                 mvnormtest_0.1-9              fastICA_1.2-0                
[16] sn_1.5-0                      kernlab_0.9-25                cubature_1.3-8               
[19] gss_2.1-7                     Rglpk_0.6-2                   Rsolnp_1.16                  
[22] quadprog_1.5-5                slam_0.1-40                   corrplot_0.77                
[25] Rcpp_0.12.10                  gdata_2.17.0                  mvoutlier_2.0.8              
[28] sgeostat_1.0-27               bcp_4.0.0                     rneos_0.3-2                  
[31] XML_3.98-1.7                  RCurl_1.95-4.8                bitops_1.0-6                 
[34] stabledist_0.7-1              devtools_1.13.1               DEoptimR_1.0-8               
[37] packrat_0.4.8-16              TTR_0.23-1                    gplots_3.0.1                 
[40] xts_0.10-0                    zoo_1.8-0                     XLConnect_0.2-12             
[43] XLConnectJars_0.2-12          fPortfolio_3022.82            fAssets_3011.83              
[46] fBasics_3022.88               timeSeries_3022.101.2         timeDate_3012.100            

loaded via a namespace (and not attached):
 [1] minqa_1.2.4           colorspace_1.3-2      class_7.3-14          modeltools_0.2-21     rprojroot_1.2        
 [6] mclust_5.2.3          pls_2.6-0             MatrixModels_0.4-1    cvTools_0.3.2         flexmix_2.3-14       
[11] mvtnorm_1.0-6         splines_3.4.0         sROC_0.1-2            mnormt_1.5-5          robustbase_0.92-7    
[16] knitr_1.15.1          nloptr_1.0.4          robCompositions_2.0.3 pbkrtest_0.4-7        rJava_0.9-8          
[21] cluster_2.0.6         png_0.1-7             rrcov_1.4-3           compiler_3.4.0        backports_1.0.5      
[26] Matrix_1.2-10         lazyeval_0.2.0        htmltools_0.3.6       quantreg_5.33         tools_3.4.0          
[31] gmp_0.5-13.1          gtable_0.2.0          trimcluster_0.1-2     nlme_3.1-131          fpc_2.1-10           
[36] lmtest_0.9-35         stringr_1.2.0         laeken_0.4.6          lme4_1.1-13           spatial_7.3-11       
[41] gtools_3.5.0          MASS_7.3-47           scales_0.4.1          VIM_4.7.0             parallel_3.4.0       
[46] SparseM_1.77          RColorBrewer_1.1-2    memoise_1.1.0         ggplot2_2.2.1         stringi_1.1.5        
[51] reshape_0.8.6         pcaPP_1.9-61          e1071_1.6-8           caTools_1.17.1        boot_1.3-19          
[56] truncnorm_1.0-7       prabclus_2.2-6        matrixStats_0.52.2    evaluate_0.10         lattice_0.20-35      
[61] GGally_1.3.0          magrittr_1.5          plyr_1.8.4            withr_1.0.2           mgcv_1.8-17          
[66] sp_1.2-4              nnet_7.3-12           tibble_1.3.0          car_2.1-4             KernSmooth_2.23-15   
[71] rmarkdown_1.5         data.table_1.10.4     vcd_1.4-3             digest_0.6.12         diptest_0.75-7       
[76] numDeriv_2016.8-1     munsell_0.4.3  

Totally irrelevant here, but on my to-do list is to install the ATLAS-BLAS and make R use it...
Many thanks
thomas

**Comment by joshuaulrich** [comment] 2017-05-26 20:57
@tchevri Thanks for the follow-up. By any chance, did you try restarting RStudio before you found the solution of closing RStudio, deleting the xts package folder, then restarting RStudio and reinstalling xts?

**Comment by tchevri** [comment] 2017-10-21 17:21
sorry for the obnoxious delay in responding.  Terribly sorry.  
YES,  absolutely, I had tried restarting RStudio - actually did so many times, because this error was very frustrating!  But did not solve anything - only your suggested solution helped me - do a clean (?) reinstall.  I am now frustrated with PerformanceAnalytics and will post there - i think you are also working on that package - you seem to be involved with every package I find useful!!! Thank you very much for that!  and again so sorry for not responding more swiftly - i feel crappy about it, given how prompt and helpful you are.
