### ISSUE TITLE
timeBasedSeq creates duplicate values due to DST 

### ISSUE THREAD

**Issue by kaiminglee** [joshuaulrich/xts#159] opened 2016-11-08 22:05 UTC
I just got bitten by this bug: https://github.com/joshuaulrich/xts/issues/67. The fix was committed 1.5 year ago, but still hasn't made it to any release version. Is a new release coming any time soon? For production I can only use CRAN packages.

**Comment by joshuaulrich** [comment] 2016-11-08 22:06
Closing as duplicate of #67.

Please do not create an issue to ask a question.

**Closed by joshuaulrich** 2016-11-08 22:06 UTC
Labels: duplicate
