### ISSUE TITLE
build failure when building against R-3.1

### ISSUE THREAD

**Issue by nieder** [joshuaulrich/xts#286] opened 2019-01-25 10:45 UTC
### Description

When building xts against R-3.1, this error occurs:
````
** installing vignettes
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'xts', details:
  call: register_s3_method("timeSeries", "as.timeSeries", "xts")
  error: could not find function "isNamespaceLoaded"
Error: loading failed
Execution halted
ERROR: loading failed
````

### Session Info

```r
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin16.7.0 (64-bit)
Running under: OS X 10.12.6 (unknown)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
```

Everything builds on R >= 3.2

**Comment by joshuaulrich** [comment] 2019-01-25 11:39
Thanks for the report.  Does this cause an actual problem for you, or are you reporting it as an artifact of testing you're doing?

**Comment by nieder** [comment] 2019-01-26 11:59
I'm a maintainer for the Fink package manager (on macOS). We have R-xts-0.10-0 building on R-3.1 to 3.5. But this error happens with 0.11-2 on R-3.1. We can keep R-3.1 at 0.10-0 and update the other variants. So it's a not a critical problem.

**Comment by joshuaulrich** [comment] 2020-08-08 15:09
I took a quick look and the problem is because `isNamespaceLoaded()` was introduced in R-3.2.0.  Perhaps you can add the dependency on your end?

I'm going to close this, since it isn't a critical issue.  Please feel free to re-open if necessary.

**Closed by joshuaulrich** 2020-08-08 15:09 UTC
