### ISSUE TITLE
Calling last on 1-row xts object with character `n` always errors

### ISSUE THREAD

**Issue by SamoPP** [joshuaulrich/xts#107] opened 2015-06-23 20:59 UTC
The original report is below. The root cause is in `last.xts`. Basically, `last.xts` with a character `n` on a one-row xts object will never be happy:

``` r
R> last(.xts(1,1), '1 second')
Error in periodicity(x) : can not calculate periodicity of 1 observation
```

---

``` r
> library(quantmod)
Loading required package: xts
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: TTR
Version 0.4-0 included new data defaults. See ?getSymbols.
> 
> SPY <- getSymbols("SPY", from="1990-01-01", auto.assign=FALSE)
    As of 0.4-0, ‘getSymbols’ uses env=parent.frame() and
 auto.assign=TRUE by default.

 This  behavior  will be  phased out in 0.5-0  when the call  will
 default to use auto.assign=FALSE. getOption("getSymbols.env") and 
 getOptions("getSymbols.auto.assign") are now checked for alternate defaults

 This message is shown once per session and may be disabled by setting 
 options("getSymbols.warning4.0"=FALSE). See ?getSymbols for more details.
> SPY <- adjustOHLC(SPY)
> 
> SPY.lastWeekOfMonth <- lapply(split(SPY, "months"), last, "1 week")
 Hide Traceback

 Rerun with Debug
 Error in periodicity(x) : can not calculate periodicity of 1 observation 
5 stop("can not calculate periodicity of 1 observation") at xts.R#244
4 periodicity(x) 
3 last.xts(X[[i]], ...) at last.R#23
2 FUN(X[[i]], ...) 
1 lapply(split(SPY, "months"), last, "1 week") 

> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-4 TTR_0.22-0     xts_0.9.874    zoo_1.7-10    

loaded via a namespace (and not attached):
[1] tools_3.2.1     grid_3.2.1      lattice_0.20-31
```

**Comment by joshuaulrich** [comment] 2015-06-23 21:04
Not a bug. There's only one observation for January, 1993. Hence the error.  It works if you remove the first row of `SPY`.

```r
SPY.lastWeekOfMonth <- lapply(split(SPY[-1,], "months"), last, "1 week")
```

**Comment by joshuaulrich** [comment] 2015-07-05 19:15
Updated with more detail into the actual problem, which wasn't clear from the initial report.

**Comment by joshuaulrich** [comment] 2020-08-08 17:40
This error was converted to a warning as part of #230. Closing as a duplicate, since the warning is warranted and does not stop code from running.

**Closed by joshuaulrich** 2020-08-08 17:40 UTC
Labels: bug
