### ISSUE TITLE
Comparing xts objects with 'Date' indices gives warnings

### ISSUE THREAD

**Issue by baoyunfan** [joshuaulrich/xts#258] opened 2018-07-24 05:58 UTC
### Description

Comparing xts objects with 'Date' indices gives warnings. The resultant xts object's index seems to be changed to 'POSIXct'.

### Expected behavior

Warning message:
timezone of object (UTC) is different than current timezone ().

### Minimal, reproducible example

```r
library(xts)
a <- xts(1:5, order.by = Sys.Date()+1:5)
b <- xts(5:1, order.by = Sys.Date()+1:5)
res <- a < b
print(res)
print(zoo::index(a))
print(zoo::index(res))

```

### Session Info

```r
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xts_0.11-0 zoo_1.8-3 

loaded via a namespace (and not attached):
[1] compiler_3.5.0  tools_3.5.0     yaml_2.1.19     grid_3.5.0      lattice_0.20-35
```

**Comment by braverock** [comment] 2018-07-24 11:48
Your warning (not an error) is because all Date indices have timezone 'UTC', as has been true and documented for a while.  Your local timezone is different.

Also, you've created a false comparison.  

xts objects are always ordered by time.  You can't create an xts object with a decreasing index.

**Comment by baoyunfan** [comment] 2018-07-24 23:44
Hi Brian,

Thanks for the quick reply. There was a typo in my initial comment. I've
corrected it. The second xts object should have been created with the same
ascending index as the first one. Here's the corrected code example.

library(xts)a <- xts(1:5, order.by = Sys.Date()+1:5)b <- xts(5:1,
order.by = Sys.Date()+1:5)res <- a < b
print(res)
print(zoo::index(a))
print(zoo::index(res))


Yes, my local time zone is different than UTC. But I still don't see why
the warnings should have been thrown. I'm merely creating legit xts object
with Sys.Date() and performing innocuous comparison operations. Somehow,
the resultant xts' index is printed with explicit UTC time zone whereas the
input xts' index is not.

> print(zoo::index(a))
[1] "2018-07-26" "2018-07-27" "2018-07-28" "2018-07-29" "2018-07-30"
> print(zoo::index(res))
[1] "2018-07-26 UTC" "2018-07-27 UTC" "2018-07-28 UTC" "2018-07-29 UTC"
"2018-07-30 UTC"

Brian G. Peterson <notifications@github.com> 于2018年7月24日周二 下午7:48写道：

**Comment by joshuaulrich** [comment] 2018-07-25 11:56
This is a duplicate of #249.  [Tom Andrews' comment](https://github.com/joshuaulrich/xts/issues/249#issuecomment-405526433) illustrates why this happens:

```r
library(xts)
test <- .xts(1:5, 1:5, tclass = "Date")
attr(test > 2, "tclass")
# [1] "POSIXct" "POSIXt"
```

**Closed by joshuaulrich** 2018-07-25 11:56 UTC
