### ISSUE TITLE
Please document: xts(  , order.by )   order.by' cannot contain 'NA', 'NaN', or 'Inf'

### ISSUE THREAD

**Issue by AndreMikulec** [joshuaulrich/xts#199] opened 2017-07-15 23:23 UTC
In
```
xts_0.10-0 ( # > xts_0.9-7 )
```
The following was added sometime.

```r
> debug(xts)

debug: if (any(!is.finite(index))) stop("'order.by' cannot contain 'NA', 'NaN', or 'Inf'")
Browse[2]> index
[1]         NA         NA 1196208000         NA         NA         NA
```
That makes sense.
Please add documentation  to 'xts', 'as.xts', and 'xtsible'.
```
order.by' cannot contain 'NA', 'NaN', or 'Inf'
```
I became suprised when my xtsible returned FALSE instead of TRUE.

Thanks,
Andre

**Comment by joshuaulrich** [comment] 2017-07-16 01:30
Thanks for the report!  It was added in commit https://github.com/joshuaulrich/xts/commit/c24c682f1b2caefec7e8c273dbd368e9f3f2fed4.  I'll update the documentation to explain the rationale for the change.

**Comment by CSYMMC** [comment] 2017-07-18 23:57
I also bumped into this problem but cannot find any description in the latest version of documentation,either. Please help to add the documentation. 

Moreover, I have some questions regarding this issue. The question is the results after aggregating are different from the results by previous version. First, I have a dataset (2 columns, one is the time stamp and another is some kind of measurement for each time stamp) which contains some NA both for time stamp and values. Next, I transform the dataset into xts format in order to obtain the mean value for each week. In the previous version, it works well without the warning. After installing the latest version, the script cannot work anymore 

> because of the warning `order.by' cannot contain 'NA', 'NaN', or 'Inf'`

Therefore, I tried `na.omit()` to exclude the NA values in my dataset. The codes works now but the mean values for each week are different from the ones I got by the previous version. So how does the rules change in the latest version so that the result of aggregation changes? I really want to know the reasons why they are different and which average is correct. Thank you so much.

**Comment by braverock** [comment] 2017-07-19 04:23
NA index values are no longer 'allowed' because, by definition, if the time series is indexed by a timestamp, you must know the index value to place the observation correctly in relation to other observations.

So, @CSYMMC I don't understand how you could have a missing timestamp.  

Given your description, it sounds as though you have two time series, with different mostly overlapping indices, which should be merged via merge() or cbind() *after* conversion to xts.

**Comment by joshuaulrich** [comment] 2017-07-31 02:23
Here's my attempt to document the rationale for the change.  Feedback welcome!

> As of version 0.10-0, xts no longer allows missing values in the index.  This is because many xts functions expect all index values to be finite.  The most important of these is `merge.xts`, which is used ubiquitously.  Missing values in the index are usually the result of a date-time conversion error (e.g. incorrect format, non-existent time due to daylight saving time, etc).  Because of how non-finite numbers are represented, a missing timestamp will always be at the end of the index (except if it is `-Inf`, which will be first).

**Closed** 2017-08-16 16:13 UTC

**Comment by crazygarnett** [comment] 2021-12-30 10:14
Dear All,

I am relatively new to R programming and wonder if you could help me to address an error issue. 
Specifically, I am struggling to create a datetime index for the data frame.

Here is the code:


```{r}

# Read XAU prices data file
xau_df <- read_csv(".../XAU_USD.csv")

# Reformat date column as Date type Month/Date/Year
xau_df$date <- as.Date(xau_df$date, format = "%m/%d/%y")

# Create a Datetime index for the DataFrame

xau_xts = xts(select(xau_df,-c("date")),
             order.by = as.POSIXct(strptime(xau_df$date,"%Y-%m-%d"))) 

## error message

Error in xts(select(xau_df, -c("date")), order.by = as.POSIXct(strptime(xau_df$date, : 'order.by' cannot contain 'NA', 'NaN', or 'Inf'


```

Would you please let me know what is wrong and how to address that issue?

Many thanks.

Best,

Konstantin

**Comment by joshuaulrich** [comment] 2021-12-30 20:50
Hi Konstantin, this isn't the right place to ask your question. You can try Stackoverflow or the [R-SIG-Finance](https://stat.ethz.ch/mailman/listinfo/r-sig-finance) mailing list. You also need to provide a [*minimal* reproducible example](http://stackoverflow.com/q/5963269/271616).
