### ISSUE TITLE
as.xts error on yearly mts object

### ISSUE THREAD

**Issue by zkabat** [joshuaulrich/xts#165] opened 2017-02-08 15:37 UTC
Reproducible example:
```
ts <- ts(1:6, start = 2016, frequency = 1)
as.xts(cbind(ts, ts))
```
Error received:
"Error in xts(x.mat, order.by = order.by, frequency = frequency(x), ...) : 
  NROW(x) must match length(order.by)"

**Comment by joshuaulrich** [comment] 2017-02-08 15:45
Thanks for the report. Can you please edit to include the output from `sessionInfo()`.

**Comment by zkabat** [comment] 2017-02-08 15:52
Sure:
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.6.0   xts_0.9-7         tidyr_0.6.1       dplyr_0.5.0       scales_0.4.1     
 [6] DT_0.2            bezier_1.1        dygraphs_1.1.1.4  forecast_7.3      timeDate_3012.100
[11] zoo_1.7-14        RODBC_1.3-14      shinyBS_0.61      shiny_1.0.0   
```

**Comment by joshuaulrich** [comment] 2017-02-08 16:01
Closing as duplicate of #64.

**Closed by joshuaulrich** 2017-02-08 16:01 UTC

**Comment by zkabat** [comment] 2017-02-09 08:25
Thanks Joshua... do you have an estimation of CRAN update?
