### ISSUE TITLE
Rollapply with xts and custom function produces NA's + endpoints

### ISSUE THREAD

**Issue by donquant** [joshuaulrich/xts#175] opened 2017-04-03 23:15 UTC
Hey,

I have some inconvenient experience with my favorite xts package, when I try to use `rollapply`
function with xts data and some custom function it produces NA's. Here is an example:

```
>require(quantmod)

>getSymbols("SPY", from = "2016-01-01", to = "2016-01-10")

>customFun <- function(x) x[1] * x[2]

>rollapply(SPY[,1], 2, customFun, by = 1)

     SPY.Open
[1,]       NA
[2,]       NA
[3,]       NA
[4,]       NA
[5,]       NA
```

I can avoid this issue, for example, by using `as.numeric` before xts and than convert output back to xts, but this method unfortunately break something with data format of newer xts that result in incorrect behavior of `endpoints` function... 

So my question/suggestion is there something can be done with `rollapply` function preventing it from producing NA's ?

**Comment by joshuaulrich** [comment] 2017-04-03 23:29
Arithmetic operations always merge before performing the operation. `x[1]` and `x[2]` have no index values in common, so merging them results in an zero-width xts object.

```r
R> SPY[1,1]*SPY[2,1]
Data:
numeric(0)

Index:
numeric(0)
```

`rollapply()` returns that as `NA`.  You need to use `coredata()` on at least one of the xts objects in order for the multiplication in `customFun()` to provide the result you want.

```r
R> customFun <- function(x) x[1] * coredata(x[2])
R> rollapply(SPY[,1], 2, customFun, by = 1)
           SPY.Open
2016-01-04       NA
2016-01-05 40378.69
2016-01-06 39945.67
2016-01-07 38741.75
2016-01-08 38126.46
```

Closing as invalid, since this is not a bug.

**Closed by joshuaulrich** 2017-04-03 23:29 UTC
